- hosts: all
  roles:
    - dhcpd
  vars:
    dhcpd_bind_interface: eth0
    dhcpd_subnets:
      - subnet: 192.168.122.0
        routers: 192.168.122.1
        netmask: 255.255.255.0
        next_server: 192.168.122.1
        range: "192.168.122.20 192.168.122.30"
    dhcpd_groups:
      - filename: pxelinux.0
        hosts:
          host1:
            address: 00:11:AA:BB:CC:DD
          host2:
            address: 11:22:CC:DD:EE:EE

