---
- name: reload daemon
  command: systemctl daemon-reload
  changed_when: False

- name: restart dhcpd server
  service: name=dhcpd state=restarted

- name: restart isc-dhcp-server
  service: name=isc-dhcp-server state=restarted
